name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build (release)
        run: cross build --release --target ${{ matrix.target }}

      - name: Package tarball
        run: |
          set -eux
          BIN="target/${{ matrix.target }}/release/ruls"
          mkdir -p dist
          # strip may fail for some targets; ignore
          strip -s "$BIN" || true
          cp "$BIN" ruls
          # include README and LICENSE if present
          if [ -f README.md ] && [ -f LICENSE ]; then
            tar -czf "dist/ruls-${{ matrix.target }}-${{ github.ref_name }}.tar.gz" ruls README.md LICENSE
          else
            tar -czf "dist/ruls-${{ matrix.target }}-${{ github.ref_name }}.tar.gz" ruls
          fi

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
          generate_release_notes: true
